services:
  mysql:
    image: mysql:8.0
    container_name: fitness-tracker-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: fitness_tracker_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"

    ports:
      - "3307:3306"

    volumes:
      - fitness_tracker_mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped

    ports:
      - "1025:1025"
      - "8025:8025"

  redis:
    image: redis:8-alpine
    container_name: fitness-tracker-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

  app:
    build: .
    container_name: fitness-tracker-api
    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy
      mailpit:
        condition: service_started
      redis:
        condition: service_started

    ports:
      - "8080:8080"

    environment:
      DB_URL: jdbc:mysql://mysql:3306/fitness_tracker_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

      SPRING_JPA_HIBERNATE_DDL_AUTO: validate

      SPRING_MAIL_HOST: mailpit
      SPRING_MAIL_PORT: 1025
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "false"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "false"

      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:
  fitness_tracker_mysql_data: